apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-k8s-config
  namespace: nitte
data:
  config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
      log_level: warn

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push
        tenant_id: default
        headers:
          X-Promtail-Api-Key: promtail-loki-secret

    scrape_configs:
      - job_name: pod-logs
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - nitte
        relabel_configs:
          - source_labels: ['__meta_kubernetes_pod_node_name']
            target_label: '__host__'
          - source_labels: ['__meta_kubernetes_namespace']
            target_label: namespace
          - source_labels: ['__meta_kubernetes_pod_name']
            target_label: pod
          - source_labels: ['__meta_kubernetes_pod_container_name']
            target_label: container
          - source_labels: ['__meta_kubernetes_pod_label_app']
            target_label: service
          - source_labels: ['__meta_kubernetes_pod_label_app']
            target_label: job
        pipeline_stages:
          - cri: {}
          - labeldrop:
              - filename
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: nitte
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: promtail
        image: grafana/promtail:2.9.4
        imagePullPolicy: IfNotPresent
        args: ["-config.file=/etc/promtail/config.yml"]
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail/config.yml
          subPath: config.yml
          readOnly: true
        - name: pods-logs
          mountPath: /var/log/pods
          readOnly: true
        - name: containers-logs
          mountPath: /var/log/containers
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: promtail-config
        configMap:
          name: promtail-k8s-config
          items:
          - key: config.yml
            path: config.yml
      - name: pods-logs
        hostPath:
          path: /var/log/pods
      - name: containers-logs
        hostPath:
          path: /var/log/containers
