apiVersion: v1
kind: Secret
metadata:
  name: nitte-secrets
  namespace: nitte
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "password"
  JWT_SECRET: "super-secret-key-change-in-production"
  RAZORPAY_KEY_ID: "rzp_test_SkyURyeOfwXob0"
  RAZORPAY_KEY_SECRET: "5oyFiJoBoScZ3wFDq2wgm4lq"
  KEYCLOAK_CLIENT_SECRET: "nitte-client-secret"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "admin123"
  NEXUS_INITIAL_PASSWORD: "nexus-admin-123"
  JENKINS_NEXUS_PASSWORD: "nexus-admin-123"
  PROMTAIL_API_KEY: "promtail-loki-secret"
  MONGO_APP_USERNAME: "app_writer"
  MONGO_APP_PASSWORD: "app_writer_pass"
  MONGO_UI_PASSWORD: "admin123"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin123"
