server:
  http_listen_port: 9081
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions-keycloak.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: keycloak-admin
    headers:
      X-Promtail-Api-Key: promtail-loki-secret

scrape_configs:
  - job_name: keycloak-audit-file
    static_configs:
      - targets: [localhost]
        labels:
          service: keycloak
          type: audit
          __path__: /var/log/keycloak/*.log
    pipeline_stages:
      - regex:
          expression: '^\S+ (?P<level>\w+) \[(?P<logger>[^\]]+)\]'
      - labels:
          level:
